### ISSUE TITLE
cannot find `$MOLMOD_DATA/setup_2022.sh`

### ISSUE THREAD

**Issue by skr3178** [haddocking/haddocking.github.io#626]
### Sorry this is on a older repository from your lab which is not maintained. I am trying to run this tutorial.

Cannot find this file setup.sh on my "EVENTS" folder in NMR box
![image](https://user-images.githubusercontent.com/79299617/211479972-5804ea83-38a9-4323-b699-948d9d0a4cac.png)

### Expected Behavior

https://www.bonvinlab.org/education/molmod_online/simulation/

**Comment by amjjbonvin** [comment]
Dear @skr3178 

Thanks for your note. This was a master course and the data were provided especially for it. We will provide the scripts and data as a link on the web page. But you will have to check and possibly edit the `setup_2022.sh` file since software version and locations might have changed on NMRBox.

**Comment by skr3178** [comment]
Dear @amjjbonvin ,

Thank you for taking the time to respond. 
I wait for the scripts and data to complete the course. 
Thanks,

**Comment by amjjbonvin** [comment]
All data and scripts for the 2022 version of this tutorial can still be found on NMRBox in `/tutorial/workshops/2022-UU-MD/molmod`  

You will find there the `setup_2022.sh` script, but you will have to edit it to change the paths  (and also check the `bashrc` file)

We are updating the tutorial for this year's course and will also provide the required scripts/data as a separate archive for download.

**Comment by skr3178** [comment]
> All data and scripts for the 2022 version of this tutorial can still be found on NMRBox in `/tutorial/workshops/2022-UU-MD/molmod`
> 
> You will find there the `setup_2022.sh` script, but you will have to edit it to change the paths (and also check the `bashrc` file)
> 
> We are updating the tutorial for this year's course and will also provide the required scripts/data as a separate archive for download.


The tutorials folder seems to be missing.
Current machine
VM:silver.nmrbox.org.
![image](https://user-images.githubusercontent.com/79299617/212215326-5c680b5e-4a33-492e-bd6f-87ae85093c20.png)

**Comment by amjjbonvin** [comment]
You are looking in the wrong place. I indicated /tutorials which is not in your home directory…
