### ISSUE TITLE
change clustering parameters' names in haddock3 tutorials

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddocking.github.io#662]
if PR https://github.com/haddocking/haddock3/pull/769 gets merged, some parameters' names must be changed also in the haddock3 tutorials

**Comment by sverhoeven** [comment]
The PR has been merged and the workflow in the tutorial now gives error that `threshold`  does not exist in clustfcc module when uploaded to https://i-vresse-workflow-builder.netlify.app/

**Comment by sverhoeven** [comment]
Also the workflow uses expert expertise parameters which makes it harder to use in the haddock3-webapp as not everyone will have the expert or guru expertise level.

* randremoval in rigidbody and flexref
* tolerance in flexref

**Comment by amjjbonvin** [comment]
Then we should make a note that users need expert access to run this tutorial

**Comment by mgiulini** [comment]
> The PR has been merged and the workflow in the tutorial now gives error that `threshold` does not exist in clustfcc module when uploaded to https://i-vresse-workflow-builder.netlify.app/

that's because the PR in this repo hasn't been merged
