### ISSUE TITLE
Unavailable Video on HADDOCK3 tutorials 

### ISSUE THREAD

**Issue by AnnaKravchenko** [haddocking/haddocking.github.io#674]
On `https://www.bonvinlab.org/education/HADDOCK3` there is a bullet point `Recording of the HADDOCK3 tutorial given at the [2022 EU-ASEAN HPC school](https://www.hpcschool.net/) in Bangkok (Dec. 5-10)` 

The video is private and thus not available. Is there a way to make it public again? 

Otherwise, should we remove this bullet point or at least `View recording` button? 

![image](https://github.com/haddocking/haddocking.github.io/assets/10245196/682d7f67-f9e2-4db9-a80c-c157f33775b1)

**Comment by amjjbonvin** [comment]
Good point - will remove it then as we don't have control on the accessibility of this video.
